config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'search/search'

  resources :users
  resources :apartments

  root 'apartments#index'

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  belongs_to :users
  geocoded_by :address
  after_validation :geocode
  has_attached_file :image, styles: { medium: "300x300>", large: "600x600>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  resourcify
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
    @pindrop = Gmaps4rails.build_markers(@apartments) do |apartment, marker|
      marker.lat apartment.latitude
      marker.lng apartment.longitude
      marker.infowindow apartment.address
    end
    @user = User.all
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
    @apartments = Apartment.all
    @hash = Gmaps4rails.build_markers(@apartments) do |apartment, marker|
      marker.lat apartment.latitude
      marker.lng apartment.longitude
    end
    @pindrops = @hash.to_json
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:latitude, :longitude, :address, :name, :contact, :bed, :bath, :price, :description, :image, :user_id)
    end

end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_form.html.erb
<%= form_for @apartment, html: { multipart: true } do |f| %>
  <%= f.file_field :image %>
  <% if @apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% @apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id, required: true %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :bed %><br>
    <%= f.text_field :bed %>
  </div>
  <div class="field">
    <%= f.label :bath %><br>
    <%= f.text_field :bath %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form' %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Apartments</h1>
<h3>Search Apartments</h3>
<form action="/search/search" method="get">
  <p><input type="text" name="query" placeholder="Search apartments"/></p>
</form>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Address</th>
      <th>Name</th>
      <th>Contact</th>
      <th>Bed</th>
      <th>Bath</th>
      <th>Price</th>
      <th>Description</th>
      <th>Image</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= image_tag @user.find(apartment.user_id).avatar.url(:thumb) %></td>
        <td><%= apartment.address %></td>
        <td><%= apartment.name %></td>
        <td><%= apartment.contact %></td>
        <td><%= apartment.bed %></td>
        <td><%= apartment.bath %></td>
        <td><%= apartment.price %></td>
        <td><%= apartment.description %></td>
        <td><%= image_tag apartment.image.url(:thumb) %></td>
        <td><%= link_to 'Show', apartment %></td>
        <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
        <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apartment', new_apartment_path %>

<br>


<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({
    provider: {},
    internal: {id: 'map'}
  },
  function() {
    markers = handler.addMarkers(<%=raw @pindrop.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(12);
  }
);
</script>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form' %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>  <%= link_to image_tag(@apartment.image.url(:large)), @apartment.image.url %> </p>

<p>
  <strong>Latitude:</strong>
  <%= @apartment.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @apartment.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @apartment.address %>
</p>

<p>
  <strong>Name:</strong>
  <%= @apartment.name %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @apartment.contact %>
</p>

<p>
  <strong>Bed:</strong>
  <%= @apartment.bed %>
</p>

<p>
  <strong>Bath:</strong>
  <%= @apartment.bath %>
</p>

<p>
  <strong>Price:</strong>
  <%= @apartment.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @apartment.description %>
</p>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": <%= @apartment.latitude %>,
      "lng": <%= @apartment.longitude %>,
      "infowindow": "hello!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

<script>
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
</script>

<%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<%= link_to 'Back', apartments_path %>